In [8]:
import numpy as np

In [9]:
a = np.array([
        [3, 2, 3],
        [6, 1, 4],
        [7, 8, 5],
            ])
# a = a.T

In [10]:
def SVD(a):
    u, s, vt = np.linalg.svd(a)
    smat = np.diag(s)
    if a.shape[0] >= a.shape[1]:
        smat = np.concatenate((smat, np.zeros((u.shape[0] - vt.shape[0], vt.shape[0]))), axis=0)
    else:
        smat = np.concatenate((smat, np.zeros((u.shape[0], vt.shape[0] - u.shape[0]))), axis=1)
    
    return u, smat, vt

In [11]:
U, S, VT = SVD(a)

In [12]:
U, S, VT

(array([[-0.32677226, -0.15913627, -0.93160911],
        [-0.46716698, -0.82968087,  0.30558904],
        [-0.82156856,  0.53507504,  0.19677349]]),
 array([[14.08852541,  0.        ,  0.        ],
        [ 0.        ,  3.74079755,  0.        ],
        [ 0.        ,  0.        ,  0.72103086]]),
 array([[-0.67674212, -0.54606566, -0.49379387],
        [-0.45711343,  0.83742754, -0.29960379],
        [ 0.57711993,  0.02296531, -0.81633644]]))

In [13]:
U.dot(S.dot(VT))

array([[3., 2., 3.],
       [6., 1., 4.],
       [7., 8., 5.]])

In [14]:
np.allclose(a, U.dot(S.dot(VT)))

True