In [1]:
import numpy as np

In [48]:
a = np.array([
        [3, 2],
        [6, 1],
        [7, 8],
            ])
# a = a.T

In [49]:
def SVD(a):
    u, s, vt = np.linalg.svd(a)
    smat = np.diag(s)
    if a.shape[0] >= a.shape[1]:
        smat = np.concatenate((smat, np.zeros((u.shape[0] - vt.shape[0], vt.shape[0]))), axis=0)
    else:
        smat = np.concatenate((smat, np.zeros((u.shape[0], vt.shape[0] - u.shape[0]))), axis=1)
    
    return u, smat, vt

In [50]:
U, S, VT = SVD(a)
U, S, VT

(array([[-0.29210226, -0.10901181, -0.95015404],
        [-0.42776966, -0.87367467,  0.23174489],
        [-0.85538844,  0.47414028,  0.2085704 ]]),
 array([[12.2735224 ,  0.        ],
        [ 0.        ,  3.51577132],
        [ 0.        ,  0.        ]]),
 array([[-0.76837305, -0.64000223],
        [-0.64000223,  0.76837305]]))

In [51]:
U.dot(S.dot(VT))

array([[3., 2.],
       [6., 1.],
       [7., 8.]])

In [52]:
np.allclose(a, U.dot(S.dot(VT)))

True